#!/bin/bash

set -e

while :
  do
    read line
    brightness=$(xrandr --verbose | grep -m 1 -w "eDP-1-1 connected" -A8 | grep "Brightness" | tr -cd '[.[:digit:]]')
    block="{\"markup\":\"pango\", \"full_text\":\"<span background='#a3be8c'> Bright. $brightness </span>\"}"
    echo "${line/\[\{/\[$block,\{}"|| exit 1
done
